### ISSUE TITLE
error importing pxr.Tf (or... why does the stub pxr module exist?)

### ISSUE THREAD

**Issue by elrond79** [AnimalLogic/AL_USDMaya#11]
Noticed that if you start up maya + AL_USDMaya in a context without `pkg_resources`, and where `AL_USDMaya_ROOT/lib/python` is on the PYTHONPATH before `USD_ROOT/lib/python`, then try:

```
import pxr.Tf
```

...it will fail because of the stub `pxr/__init__.py` installed by AL_USDMaya.

This could be fixed by modifying the stub `pxr/__init__.py` to fallback to using `pkg_util.extend_path` (as it does in other places)... but the bigger question is... why do we even need this stub pxr module? All it seems to do is set `__all__ = []`.  There are no other files in the module.  Why do we need to set `__all__` to an empty list?

**Comment by fabal** [comment]
Thanks for the heads up. `pxr` is a leftover and needs to be removed.

**Comment by elrond79** [comment]
Ah, that makes more sense. =)

**Comment by fabal** [comment]
Fixed in 3b00078c49c4b7a747f45081edc0407f790ec774
