### ISSUE TITLE
Building in Centos7 and ‘UsdSchemaType’ does not name a type

### ISSUE THREAD

**Issue by ericgd** [AnimalLogic/AL_USDMaya#117]
Greetings,
First time posting in this forum.

I am trying to build AL_USDMaya with Maya2018sp4, Centos7 and CMake.
Everything seems to be going well, but at 85% of the build, I get a type definition error:

--start--
In file included from AL_USDMaya-master/schemas/AL/usd/schemas/ModelAPI.cpp:24:0:
AL_USDMaya-master/schemas/AL/usd/schemas/./ModelAPI.h:67:18: error: ‘UsdSchemaType’ does not name a type
     static const UsdSchemaType schemaType = UsdSchemaType::NonAppliedAPI;
                  ^
AL_USDMaya-master/schemas/AL/usd/schemas/./ModelAPI.h:116:13: error: ‘UsdSchemaType’ does not name a type
     virtual UsdSchemaType _GetSchemaType() const;
             ^
AL_USDMaya-master/schemas/AL/usd/schemas/ModelAPI.cpp:65:1: error: ‘UsdSchemaType’ does not name a type
 UsdSchemaType AL_usd_ModelAPI::_GetSchemaType() const {
 ^
make[2]: *** [schemas/AL/usd/schemas/CMakeFiles/AL_USDMayaSchemas.dir/ModelAPI.cpp.o] Error 1
make[1]: *** [schemas/AL/usd/schemas/CMakeFiles/AL_USDMayaSchemas.dir/all] Error 2
---stop---

I could not find anybody else with this error... Which tells me the problem is not the code but maybe my environment. Any idea how to fix it?

**Comment by murphyeoin** [comment]
This is the same bug reported in https://groups.google.com/forum/#!topic/al_usdmaya-discussion/j7OZ7iaAyY0, so I'm going to close this ticket - please re-open if I'm mistaken.
Eoin
