### ISSUE TITLE
maya/MTypes.h missing in 2018

### ISSUE THREAD

**Issue by akrilfx** [AnimalLogic/AL_USDMaya#120]
Hello guys,
Just wanted to point out that this file `include/maya/MTypes.h ` mentioned in `cmake/modules/FindMaya.cmake` is actually missing since Maya 2018.

https://github.com/PixarAnimationStudios/USD/issues/265

thanks.

**Comment by murphyeoin** [comment]
Thanks! We'll take a look

**Comment by fabal** [comment]
Hi @akrilfx , sorry for the delay. I don't think this file should be missing from your Maya 2018 devkit.
Just to clarify, the pixar's issue you're refering to is about the namespacing that has been introduced in maya's devkit since Maya 2018.
Let me know if I'm missing something.

**Comment by murphyeoin** [comment]
I'll close this, feel free to re-open if it seems relevant. Thanks
