### ISSUE TITLE
Rename MayaReference to AL_usd_MayaReference

### ISSUE THREAD

**Issue by JasonGilholme** [AnimalLogic/AL_USDMaya#15]
https://github.com/AnimalLogic/AL_USDMaya/blob/develop/translators/MayaReference.h

MayaReference should be called AL_usd_MayaReference to match up with the call to AL_USD_MAYA_DEFINE_TRANSLATOR here:  https://github.com/AnimalLogic/AL_USDMaya/blob/develop/translators/MayaReference.cpp#L46

**Comment by fabal** [comment]
Are you getting an error or is this more a suggestion?

**Comment by JasonGilholme** [comment]
Yeah I get an error at the line I linked to saying that AL_usd_MayaReference is undefined.  

I'm not sure of the scope in which the translators are defined for maya so Im assuming that a more specific name would be better.  This is why I've renamed the class in my clone rather than updating the registration call.

**Comment by fabal** [comment]
Fixed in d165134158224136a545586f1b477aff0ba1d928
