### ISSUE TITLE
Wiki comparison page correction

### ISSUE THREAD

**Issue by mrharris** [AnimalLogic/AL_USDMaya#158]
Just a minor correction since I saw this page (https://github.com/AnimalLogic/AL_USDMaya/wiki/AL_USDMaya-and-pxrUSDMaya-Feature-Sets) is getting some updates currently...

There is a section that states pxrUsd does not support usd driven maya mesh nodes

"AlembicMaya" style Animated Geometry Cache | yes | no | see docs
-- | -- | -- | --

However, if I'm not mistaken that functionality has since been implemented here https://github.com/PixarAnimationStudios/USD/commit/3e33d91351a0eef1c9ca3374b2d70cb0f18d200a

**Comment by murphyeoin** [comment]
Thanks @mrharris ! Missed that - I will update..
