### ISSUE TITLE
Is MayaReference Translator in the correct location?

### ISSUE THREAD

**Issue by JasonGilholme** [AnimalLogic/AL_USDMaya#16]
To build the translators I had to alter this include:  https://github.com/AnimalLogic/AL_USDMaya/blob/develop/translators/MayaReference.cpp#L29

Based on the DgNodeTranslator above it, should the MayaReference Translator be moved into AL/usdmaya/filio/translators  ??

**Comment by fabal** [comment]
Thanks for reporting this, we have a fix coming soon for this issue.

As a side note, the MayaReference translator is built as USD plugin, mainly to serve as an example. That's the reason why it's in a separate location.

**Comment by JasonGilholme** [comment]
Ahh I see.  Thanks.

**Comment by fabal** [comment]
Fixed in d165134158224136a545586f1b477aff0ba1d928
