### ISSUE TITLE
Manually selecting the parent of an already selected transform is causing a maya error

### ISSUE THREAD

**Issue by sirpalee** [AnimalLogic/AL_USDMaya#22]
How to reproduce the issue:
- Load up an usd file into a proxy with several levels of prims.
- Use the proxy shape select to select one of the prims in the deeper levels.
- Open the outliner and click on one of its parents.

Explanation.
This whole issue starts from the OnSelectionChanged callback. Whenever the user clicks on the outliner, the second branch is executed in `ProxyShape::onSelectionChanged` (i.e., selectionMode is zero). This ends up calling AL_usdmaya_ProxyShapeSelect, and passes the prims that are not in the current selection list as parameters. Since the active selection list is already updated to the new one, it contains one of the parent prims, so the previously selected prim is about to be removed.

This jumps through a couple of functions and ends up in `ProxyShape::removeUsdTransformChain_internal`.

Here, the prim passed to the command is getting deleted, and all of its parent prims. However, this deletes the prim that was just selected. And Maya throws an error.

My initial pass at the problem was not to delete objects that are in the current selection list. (pseudocode below)

```cpp
MSelectionList sl;
MGlobal::getActiveSelectionList(sl);
...
if(it->second.checkRef(reason))
{
  MObject object = it->second.m_node;
  MFnDagNode dgNode(object);
  MDagPath dg;
  dgNode.getPath(dg);
  if (sl.hasItem(dg)) { return; }
  ...
```

However, this approach does not take branches in the hierarchy account. Ie, the usd file looks something like this

```
- A
  - B
    - C
    - D
```
We have both C and D selected, and the user deselects C in the UI. That'll trigger deletion of C, and because none of its parent transforms is selected, all of them are going to be selected.

While the snippet above added to the code helps the first time a parent is selected, the second time it fails too. (none of the transforms are removed, and the stuck around) That happens, because proxy->selectedPaths is going to be empty, and the selection command exits early.

I tried to force reselection of the nodes that are part of the active selection list in the onSelectionChanged callback to ensure they still exist / / maintained properly in the internal selection lists, but that created other problems.

So far it looks like this issue is a general problem of how the selections are tracked. Unless I missed something very trivial in other parts of the pipe.

Any feedback would be greatly appreciated.

**Comment by elrond79** [comment]
I believe this has been fixed / merged, so you can close this issue...
