### ISSUE TITLE
Update for Usd v0.8.1

### ISSUE THREAD

**Issue by alekamca** [AnimalLogic/AL_USDMaya#29]
Very little appears to be affected by the API changes to Usd v0.8.1. I believe these are the required changes: Update build settings to accommodate the optional use of python. Remove calls to UsdStage::Close(). Change one test example's call from UsdRelationship::AppendTarget to UsdRelationship::AddTarget.

**Comment by fabal** [comment]
AL_USDMaya is using USD-0.8.1 since 0.24.4 (the master branch has been updated).
Thanks Aleka.
